# Generated by Django 4.1.3 on 2022-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_remove_quiz_attempts_remove_quiz_user_quiztopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztopic',
            name='failed',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiztopic',
            name='passed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
